#!/bin/bash

# External Services Setup Script
# Helps set up required external services for Aicitel

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "🔧 Aicitel External Services Setup Guide"
echo "========================================="
echo ""

# Function to print section headers
print_section() {
    echo -e "${BLUE}$1${NC}"
    echo "-------------------"
}

# Function to print instructions
print_step() {
    echo -e "${GREEN}→${NC} $1"
}

print_section "1. HubSpot CRM Setup (Optional but Recommended)"
echo ""
print_step "1. Go to https://app.hubspot.com"
print_step "2. Navigate to: Settings → Integrations → Private Apps"
print_step "3. Click 'Create private app'"
print_step "4. Name it: 'Aicitel Web Integration'"
print_step "5. Go to 'Scopes' tab and enable:"
echo "     - crm.objects.contacts.read"
echo "     - crm.objects.contacts.write"
print_step "6. Click 'Create app' and copy the access token"
print_step "7. Also copy your Hub ID from: Settings → Account Setup → Account Defaults"
echo ""
echo "Add to your .env.local:"
echo "HUBSPOT_API_KEY=pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
echo "HUBSPOT_PORTAL_ID=12345678"
echo ""
read -p "Press Enter when HubSpot is configured (or Skip to continue)..."

print_section "2. Sentry Error Monitoring Setup"
echo ""
print_step "1. Go to https://sentry.io/signup/"
print_step "2. Create account (free tier available)"
print_step "3. Create new project → Select 'Next.js'"
print_step "4. Copy the DSN (looks like: https://xxx@xxx.ingest.sentry.io/xxx)"
print_step "5. Go to Settings → Developer Settings → Create Auth Token"
print_step "6. Copy organization slug and project name"
echo ""
echo "Add to your .env.local:"
echo "NEXT_PUBLIC_SENTRY_DSN=https://xxx@xxx.ingest.sentry.io/xxx"
echo "SENTRY_AUTH_TOKEN=your_auth_token"
echo "SENTRY_ORG=your_org_slug"
echo "SENTRY_PROJECT=your_project_name"
echo "SENTRY_ENVIRONMENT=production"
echo ""
read -p "Press Enter when Sentry is configured..."

print_section "3. Upstash Redis Setup (Required)"
echo ""
print_step "1. Go to https://console.upstash.com/"
print_step "2. Create account (free tier: 10,000 commands/day)"
print_step "3. Click 'Create Database'"
print_step "4. Choose a region close to your users"
print_step "5. Copy 'UPSTASH_REDIS_REST_URL' and 'UPSTASH_REDIS_REST_TOKEN'"
echo ""
echo "Add to your .env.local:"
echo "UPSTASH_REDIS_REST_URL=https://xxx.upstash.io"
echo "UPSTASH_REDIS_REST_TOKEN=xxxxx"
echo ""
read -p "Press Enter when Upstash is configured..."

print_section "4. Cloudflare Turnstile Setup (Required)"
echo ""
print_step "1. Go to https://dash.cloudflare.com/"
print_step "2. Sign up/login (free account)"
print_step "3. Go to Turnstile from sidebar"
print_step "4. Click 'Add site'"
print_step "5. Enter your domain or use 'localhost' for testing"
print_step "6. Choose 'Managed' mode"
print_step "7. Copy Site Key and Secret Key"
echo ""
echo "Add to your .env.local:"
echo "NEXT_PUBLIC_TURNSTILE_SITE_KEY=0x4AAAAAAA..."
echo "TURNSTILE_SECRET_KEY=0x4AAAAAAA..."
echo ""
read -p "Press Enter when Turnstile is configured..."

print_section "5. PostgreSQL Database Setup (Production)"
echo ""
echo "Choose one option:"
echo ""
echo "Option A: Neon (Recommended - Free tier: 512MB)"
print_step "1. Go to https://neon.tech/"
print_step "2. Create account and new project"
print_step "3. Copy connection string"
echo ""
echo "Option B: Supabase (Free tier: 500MB)"
print_step "1. Go to https://supabase.com/"
print_step "2. Create project"
print_step "3. Go to Settings → Database → Connection string"
echo ""
echo "Option C: Railway (Hobby Plan: ~$5/month)"
print_step "1. Go to https://railway.app/"
print_step "2. Create PostgreSQL database"
print_step "3. Copy connection URL"
echo ""
echo "Add to your backend .env:"
echo "DATABASE_CLIENT=postgres"
echo "DATABASE_URL=postgresql://user:pass@host:5432/dbname"
echo ""
read -p "Press Enter when database is configured..."

print_section "6. Strapi Backend Setup"
echo ""
print_step "1. Deploy backend to Railway/DigitalOcean/VPS"
print_step "2. Run database migrations"
print_step "3. Create admin user in Strapi"
print_step "4. Create API token: Settings → API Tokens → Create"
print_step "5. Set permissions for Applications and Inquiries"
echo ""
echo "Add to your frontend .env.local:"
echo "NEXT_PUBLIC_STRAPI_URL=https://api.yourdomain.com"
echo "STRAPI_API_TOKEN=your_api_token_here"
echo ""
read -p "Press Enter when Strapi is configured..."

print_section "7. Vercel Deployment Setup"
echo ""
print_step "1. Install Vercel CLI: npm i -g vercel"
print_step "2. Login: vercel login"
print_step "3. Link project: vercel link (in frontend directory)"
print_step "4. Add environment variables:"
echo "     vercel env pull .env.local"
echo "   Or add them in Vercel Dashboard → Settings → Environment Variables"
echo ""
read -p "Press Enter to continue..."

print_section "Setup Complete! ✅"
echo ""
echo "Next steps:"
echo "  1. Verify all environment variables are set"
echo "  2. Run: ./deploy.sh"
echo "  3. Test your production deployment"
echo ""
echo "📚 Documentation:"
echo "  - Full deployment guide: DEPLOYMENT.md"
echo "  - HubSpot setup: HUBSPOT_INTEGRATION.md"
echo "  - Production checklist: PRODUCTION_READINESS.md"
